#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use App\Console\Main;

if (PHP_SAPI !== 'cli' || isset($_SERVER['HTTP_USER_AGENT'])) {
  echo "Cli only!";
  exit;
}

require_once __DIR__ . '/bootstrap.php';

$cli = new League\CLImate\CLImate;

$driver = new Main($cli);
$driver->entrypoint();
